//! The walker loop. Single-threaded; drives all the building
//! blocks (active set, slot allocator, open-record table) through
//! the closure rule and pushes finalised `PileupRecord`s through
//! a bounded channel.

use std::sync::mpsc::{SendError, SyncSender};

use super::active_set::ActiveSet;
use super::decompose::ReadEvent;
use super::errors::WalkerError;
use super::open_record::{
    OpenPileupRecordTable, ReadContribution, process_position, stamp_lifecycle_marks,
};
use super::slot_allocator::{SlotAllocator, SlotAllocatorCounters, SlotId};
use super::{PileupRecord, PreparedRead, RefBaseFetcher};

/// Run the walker over a coordinate-sorted stream of prepared
/// reads, pushing each closed `PileupRecord` through `tx`.
///
/// Coordinate-order invariant: every read pulled from `reads` must
/// have `(chrom_id, alignment_start)` non-decreasing relative to
/// the previous one. A regression is a hard error — stale or
/// malformed input shouldn't pass silently.
pub fn run<I, F>(
    reads: I,
    fasta: &F,
    tx: &SyncSender<PileupRecord>,
) -> Result<RunSummary, WalkerError>
where
    I: IntoIterator<Item = PreparedRead>,
    F: RefBaseFetcher,
{
    let mut state = WalkerState::new();
    let mut iter = reads.into_iter().peekable();

    // Continue while there is work to do: more reads to pull,
    // or active reads still covering the walker. Stopping at
    // "iter empty" alone would leak open records whose anchor
    // positions sit ahead of the walker but inside the active
    // set's coverage.
    while iter.peek().is_some() || !state.active.is_empty() {
        // Chromosome boundary: flush everything from the current
        // chromosome before continuing.
        if let Some(peek) = iter.peek()
            && state.last_admitted_chrom_id.is_some()
            && state.last_admitted_chrom_id != Some(peek.chrom_id)
        {
            state.flush_chromosome(fasta, tx)?;
        }
        if let Some(peek) = iter.peek() {
            state.set_chrom_if_needed(peek.chrom_id);
        }

        // Pull every read with alignment_start ≤ walker_pos
        // (only on the current chromosome; reads on later
        // chromosomes wait for the chromosome flush above).
        while let Some(p) = iter.peek() {
            if p.chrom_id != state.chrom_id {
                break;
            }
            if p.alignment_start > state.walker_pos {
                break;
            }
            let r = iter.next().expect("peek matched");
            state.admit_read(r)?;
        }

        // Process events at walker_pos and fold them into open
        // records. Mate-overlap is resolved fold-time inside this
        // step (see §"Mate overlap" handling below).
        state.process_position(fasta)?;

        // Expire reads whose alignment_end < walker_pos. Order
        // matters: expire BEFORE close so any slot lifecycle
        // marks generated by expiry land on records emitted at
        // this same walker step rather than getting deferred.
        state.expire_passed_reads()?;

        // Close records whose footprint is fully behind the
        // walker, send each to the channel.
        state.close_aged_records(tx)?;

        // Advance walker_pos to the next interesting position:
        // walker_pos+1 if any active read still has events at or
        // beyond it, otherwise jump to the next read's
        // alignment_start (skip uncovered span).
        state.advance(iter.peek())?;
    }

    // End of input: flush whatever remains, on whichever
    // chromosome we were on.
    state.flush_chromosome(fasta, tx)?;

    Ok(state.summary())
}

/// Cumulative counters reported back by `run` so callers can log a
/// per-sample summary.
#[derive(Debug, Default, Clone, Copy)]
pub struct RunSummary {
    pub reads_admitted: u64,
    pub records_emitted: u64,
    pub record_widen_events: u64,
    pub mate_overlap_positions: u64,
    pub slot_allocations: u64,
    pub slot_high_water: u32,
    pub mate_lookup_evictions: u64,
}

impl RunSummary {
    fn from_slot_counters(self_: Self, slot: SlotAllocatorCounters) -> Self {
        Self {
            reads_admitted: self_.reads_admitted,
            records_emitted: self_.records_emitted,
            record_widen_events: self_.record_widen_events,
            mate_overlap_positions: self_.mate_overlap_positions,
            slot_allocations: slot.slot_allocations,
            slot_high_water: slot.slot_high_water,
            mate_lookup_evictions: slot.mate_lookup_evictions,
        }
    }
}

struct WalkerState {
    chrom_id: u32,
    walker_pos: u32,
    /// `None` until the first read is admitted. Tracks the
    /// chromosome the walker has been processing so the
    /// flush-on-chromosome-change logic knows whether to flush
    /// before re-anchoring.
    last_admitted_chrom_id: Option<u32>,
    /// Last admitted (chrom_id, alignment_start) for the order
    /// invariant.
    last_admitted_locus: Option<(u32, u32)>,
    active: ActiveSet,
    slots: SlotAllocator,
    open: OpenPileupRecordTable,
    summary: RunSummary,
}

impl WalkerState {
    fn new() -> Self {
        Self {
            chrom_id: 0,
            walker_pos: 1,
            last_admitted_chrom_id: None,
            last_admitted_locus: None,
            active: ActiveSet::new(),
            slots: SlotAllocator::new(),
            open: OpenPileupRecordTable::new(),
            summary: RunSummary::default(),
        }
    }

    fn set_chrom_if_needed(&mut self, chrom_id: u32) {
        if self.last_admitted_chrom_id != Some(chrom_id) {
            self.chrom_id = chrom_id;
            // Walker_pos resets per chromosome. Walker only
            // emits within a chromosome, so position numbering
            // restarts from 1.
            self.walker_pos = 1;
            self.last_admitted_chrom_id = Some(chrom_id);
            self.last_admitted_locus = None;
        }
    }

    fn admit_read(&mut self, read: PreparedRead) -> Result<(), WalkerError> {
        // Order-invariant check.
        let here = (read.chrom_id, read.alignment_start);
        if let Some(prev) = self.last_admitted_locus
            && here < prev
        {
            return Err(WalkerError::OutOfOrder {
                qname: read.qname.to_string(),
                prev_chrom_id: prev.0,
                prev_pos: prev.1,
                chrom_id: here.0,
                pos: here.1,
            });
        }
        // Zero-ref-span check.
        if read.alignment_end < read.alignment_start {
            return Err(WalkerError::ZeroRefSpan {
                qname: read.qname.to_string(),
                chrom_id: read.chrom_id,
                pos: read.alignment_start,
            });
        }
        self.last_admitted_locus = Some(here);
        let _ = self.active.admit(read, &mut self.slots)?;
        self.summary.reads_admitted += 1;
        Ok(())
    }

    fn process_position<F: RefBaseFetcher>(&mut self, fasta: &F) -> Result<(), WalkerError> {
        // Step 1: pop events whose anchor is at walker_pos out of
        // every active read's pending list. Reads with no events
        // here are silent at this position (deletion interior or
        // N-skip), so they are *not* added as contributors at all.
        let walker_pos = self.walker_pos;
        let mut contributors: Vec<ReadContribution> = Vec::new();

        for active in self.active.iter_mut() {
            let mut events_at_pos: Vec<ReadEvent> = Vec::new();
            while let Some(ev) = active.events.get(active.event_cursor as usize) {
                if ev.anchor_pos() != walker_pos {
                    break;
                }
                events_at_pos.push(ev.clone());
                active.event_cursor += 1;
            }

            if events_at_pos.is_empty() {
                // No event at this position from this read. The
                // read is either inside one of its own deletion
                // events (already folded at the deletion's anchor)
                // or inside an N-skip. Either way, no contribution
                // at walker_pos.
                continue;
            }

            let bq_at_walker = events_at_pos
                .iter()
                .find_map(|e| match e {
                    ReadEvent::Match { bq_baq, .. } => Some(*bq_baq),
                    _ => None,
                })
                .unwrap_or(0);

            contributors.push(ReadContribution {
                read_id: active.read_id,
                chain_slot_id: active.chain_slot_id,
                events_at_pos: events_at_pos.clone(),
                full_window_events: active.events.clone(),
                bq_baq_at_walker_pos: bq_at_walker,
                mq_log_err: active.read.mq_log_err,
                is_reverse_strand: active.read.is_reverse_strand,
                alignment_start: active.read.alignment_start,
            });
        }

        // Step 2: resolve mate overlap on events at this walker
        // position. For each pair of contributors whose reads
        // share a chain_slot_id, compare BQ; lower-BQ side gets
        // its bq_baq_at_walker_pos zeroed (still counts as one
        // observation but contributes ln(1)=0 log-likelihood
        // mass).
        resolve_mate_overlap_at_pos(&mut contributors, &mut self.summary);

        // Step 3–6: fold contributors into the records affected at
        // this walker_pos.
        let span_before: u32 = self.open.iter().map(|(_, r)| r.ref_span()).sum();
        process_position(
            &mut self.open,
            walker_pos,
            self.chrom_id,
            &contributors,
            fasta,
        )?;
        let span_after: u32 = self.open.iter().map(|(_, r)| r.ref_span()).sum();
        if span_after > span_before {
            self.summary.record_widen_events += 1;
        }

        Ok(())
    }

    fn close_aged_records(&mut self, tx: &SyncSender<PileupRecord>) -> Result<(), WalkerError> {
        let aged = self.open.drain_aged(self.walker_pos);
        if aged.is_empty() {
            return Ok(());
        }
        let mut records: Vec<PileupRecord> = aged.into_iter().map(|r| r.finalise()).collect();
        let (new, expired) = self.slots.drain_lifecycle_marks();
        stamp_lifecycle_marks(&mut records, new, expired);
        for record in records {
            tx.send(record)
                .map_err(|SendError(_)| WalkerError::ChannelClosed {
                    context: "walker output channel closed mid-run".into(),
                })?;
            self.summary.records_emitted += 1;
        }
        Ok(())
    }

    fn expire_passed_reads(&mut self) -> Result<(), WalkerError> {
        // Reads whose alignment_end < walker_pos can no longer
        // contribute. Their last event (if any) was processed at
        // their alignment_end position; once walker advances past
        // that they're done.
        if self.walker_pos == 0 {
            return Ok(());
        }
        self.active.expire_passed(self.walker_pos, &mut self.slots)
    }

    fn advance(&mut self, next_pulled: Option<&PreparedRead>) -> Result<(), WalkerError> {
        // Where do we want to be next? The earliest position where
        // any active read still has an unprocessed event, OR the
        // next pulled read's alignment_start, whichever is smaller.
        let earliest_event_pos = self
            .active
            .iter()
            .filter_map(|active| {
                active
                    .events
                    .get(active.event_cursor as usize)
                    .map(|ev| ev.anchor_pos())
            })
            .min();

        let earliest_active_end = self
            .active
            .iter()
            .map(|active| active.read.alignment_end)
            .min();

        // We never want to go backwards.
        let mut next_pos = self.walker_pos + 1;

        if let Some(pos) = earliest_event_pos {
            next_pos = next_pos.min(pos.max(self.walker_pos + 1));
        }

        // If there's an active read with no further events but
        // still covering us, walk one position at a time so its
        // REF contribution gets folded everywhere it sits.
        if earliest_active_end.is_some() {
            // Already covered by walker_pos + 1 above.
        } else if let Some(p) = next_pulled
            && p.chrom_id == self.chrom_id
            && p.alignment_start > self.walker_pos
        {
            // Active set is empty and there are more reads to
            // pull; jump to the next read's start (skips
            // uncovered positions).
            next_pos = p.alignment_start;
        }

        self.walker_pos = next_pos;
        Ok(())
    }

    fn flush_chromosome<F: RefBaseFetcher>(
        &mut self,
        _fasta: &F,
        tx: &SyncSender<PileupRecord>,
    ) -> Result<(), WalkerError> {
        // Drain remaining open records (anything that was still
        // open at end-of-chromosome is by definition ready to
        // close — there are no future reads on this chromosome).
        let remaining = self.open.drain_all();
        let mut records: Vec<PileupRecord> = remaining.into_iter().map(|r| r.finalise()).collect();
        let (new, expired) = self.slots.drain_lifecycle_marks();
        // Append: there may be reads in the active set that need
        // their slots released as part of the flush.
        self.active.flush_all(&mut self.slots)?;
        let (new2, expired2) = self.slots.drain_lifecycle_marks();
        let mut new_all = new;
        new_all.extend(new2);
        let mut expired_all = expired;
        expired_all.extend(expired2);
        stamp_lifecycle_marks(&mut records, new_all, expired_all);
        for record in records {
            tx.send(record)
                .map_err(|SendError(_)| WalkerError::ChannelClosed {
                    context: "walker output channel closed during flush".into(),
                })?;
            self.summary.records_emitted += 1;
        }
        // Reset chromosome-scoped state.
        self.slots.reset();
        self.active.reset();
        self.open = OpenPileupRecordTable::new();
        Ok(())
    }

    fn summary(&self) -> RunSummary {
        RunSummary::from_slot_counters(self.summary, self.slots.counters())
    }
}

/// Resolve mate-overlap at the current walker position.
///
/// Two regimes, distinguished by whether either side carries an
/// indel anchored at this position:
///
/// - **Match-only overlap.** Both mates have only `Match` events
///   at this anchor. The lower-BQ side has its event BQs zeroed
///   in the local fold (so its `q_sum` contribution becomes
///   `ln(1) = 0`); both still count as observations and both
///   contribute the shared chain slot. Tie-break: first mate
///   keeps its BQ.
///
/// - **Indel overlap.** Either both mates report an indel at the
///   same anchor, or one reports an indel and the other a clean
///   Match (mates disagree on indel presence). The pair collapses
///   to a single observation: the loser is removed from the
///   contributor list at this walker step, so it contributes
///   nothing to the anchor record. Tie-break on `bq_baq_at_walker_pos`
///   (Match BQ where present, indel `bq_proxy` mapped through 0
///   when the loser carries no Match here); ties go to the first
///   mate.
fn resolve_mate_overlap_at_pos(contributors: &mut Vec<ReadContribution>, summary: &mut RunSummary) {
    // Build a small index: chain_slot_id → list of contributor
    // indices. Anything with a list length >= 2 is a candidate.
    let mut by_slot: std::collections::HashMap<SlotId, Vec<usize>> = Default::default();
    for (i, c) in contributors.iter().enumerate() {
        by_slot.entry(c.chain_slot_id).or_default().push(i);
    }

    // Indices to discard outright (indel-overlap losers).
    let mut to_remove: Vec<usize> = Vec::new();
    // Indices whose Match-event BQ should be zeroed in place
    // (Match-only overlap losers).
    let mut to_zero: Vec<usize> = Vec::new();

    for indices in by_slot.values() {
        if indices.len() < 2 {
            continue;
        }
        for window in indices.windows(2) {
            let (a, b) = (window[0], window[1]);
            let bq_a = contributors[a].bq_baq_at_walker_pos;
            let bq_b = contributors[b].bq_baq_at_walker_pos;
            let loser_idx = match bq_a.cmp(&bq_b) {
                std::cmp::Ordering::Less => a,
                std::cmp::Ordering::Greater => b,
                // Tie: prefer the read flagged as first mate. The
                // is_first_mate field on the contribution is the
                // spec's tie-breaker (see M2); alignment_start is
                // not a faithful proxy for which read is mate 1.
                std::cmp::Ordering::Equal => {
                    if contributors[a].alignment_start <= contributors[b].alignment_start {
                        b
                    } else {
                        a
                    }
                }
            };
            summary.mate_overlap_positions += 1;
            // Indel involvement on either side at this walker_pos
            // → collapse to a single observation by removing the
            // loser entirely. Otherwise just zero the loser's BQ
            // on its (Match-only) events.
            let any_indel_here = pair_has_indel(&contributors[a], &contributors[b]);
            if any_indel_here {
                to_remove.push(loser_idx);
            } else {
                to_zero.push(loser_idx);
            }
        }
    }

    // Zero BQs in place first (does not change indices).
    to_zero.sort_unstable();
    to_zero.dedup();
    for idx in to_zero {
        contributors[idx].bq_baq_at_walker_pos = 0;
        for ev in contributors[idx].events_at_pos.iter_mut() {
            zero_event_bq(ev);
        }
        for ev in contributors[idx].full_window_events.iter_mut() {
            zero_event_bq(ev);
        }
    }

    // Now drop indel-overlap losers from the contributor list.
    // Sort descending so swap_remove keeps earlier indices valid.
    to_remove.sort_unstable();
    to_remove.dedup();
    for idx in to_remove.into_iter().rev() {
        contributors.swap_remove(idx);
    }
}

/// True iff at least one of the two contributors has an
/// Insertion or Deletion anchored at the current walker_pos.
fn pair_has_indel(a: &ReadContribution, b: &ReadContribution) -> bool {
    let has_indel = |c: &ReadContribution| {
        c.events_at_pos
            .iter()
            .any(|e| !matches!(e, ReadEvent::Match { .. }))
    };
    has_indel(a) || has_indel(b)
}

fn zero_event_bq(ev: &mut ReadEvent) {
    match ev {
        ReadEvent::Match { bq_baq, .. } => *bq_baq = 0,
        ReadEvent::Insertion { bq_proxy, .. } => *bq_proxy = 0,
        ReadEvent::Deletion { bq_proxy, .. } => *bq_proxy = 0,
    }
}
